### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by osv** [marmelab/ng-admin-demo#10]
Hello, I just found ng-admin, it very cool, but I have one notice. ng-admin-demo use data.js as huge data all-in-one place. Does ng-admin support pagination (with sort, search, prefetch next prev pages)? Does you have plans to add it?

**Comment by jpetitcolas** [comment]
Of course, ng-admin supports pagination. Have a look on the method available on the `listView` in the [documentation](https://github.com/marmelab/ng-admin/blob/master/doc/Configuration-reference.md#listview-settings). We simply use a big JavaScript file to prevent from mouting a real API app. 

However, there is no prefetch of previous or next pages.

**Comment by osv** [comment]
Thanks!
