### ISSUE TITLE
Is it possible to build it / run it on windows?

### ISSUE THREAD

**Issue by daniel-rosiak** [marmelab/ng-admin-demo#11]
When i type:
```
./node_modules/.bin/webpack  --progress --colors --devtool source-map
```
I get: 
```
ERROR in ./~/admin-config/lib/Field/NumberField.js
Module parse failed: [PATH]\ng-admin-demo-gh-pages\node_modules\admin-config\lib\Field\NumberField.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Field from "./Field";
|
| class NumberField extends Field {
 @ ./js/types/AmountField.js 17:38-83
```

Using: windows / node  4.2.2 / npm 2.14.7

**Comment by blacksand** [comment]
find this in webpack.config.js:
     { test: new RegExp('node_modules' + sep + 'admin-config' + sep + '.*\\.jsx?$'), loader: 'babel' },

replace with:
     { test: /node_modules\\|\/admin-config\\|\/.*\.jsx?$/, loader: 'babel' },

**Comment by daniel-rosiak** [comment]
Wow, works. Thanks :+1:

**Comment by jpetitcolas** [comment]
Indeed, there may be some issues with paths. We should definitily use some `path.join`.
