### ISSUE TITLE
Dashboard widgets

### ISSUE THREAD

**Issue by luismareze** [marmelab/ng-admin-demo#13]
Hi,

I just run the code posted here and I am getting this page found. What Can I do to run the widgets in front of my dashboard?

http://prntscr.com/9umcq8
![screenshot_1](https://cloud.githubusercontent.com/assets/13120053/12555674/6a0b28e4-c369-11e5-9478-49e9337e84ca.png)

**Comment by fzaninotto** [comment]
What did you click on to get his page not found error? What is the current URL?

P.S.: you can paste images directly in GitHub issues, it's easier for me than to go to another service.

**Comment by luismareze** [comment]
Thanks. 
I just clone the repo and run the index.html and I got this "page not found" message.

**Comment by alexisjanvier** [comment]
Did you run `make data` ?

**Comment by fzaninotto** [comment]
I cannot reproduce this issue. What is your platform? Do any of the other pages work?

**Comment by Kmaschta** [comment]
I close it for lack of feedback.

Feel free to open it again if you can reproduce the issue.
