### ISSUE TITLE
Please add layout override

### ISSUE THREAD

**Issue by sajov** [marmelab/ng-admin-demo#15]
Can you add the Original layout as custom layout override
Would be great
Thx

**Comment by fzaninotto** [comment]
The original layout is available at https://github.com/marmelab/ng-admin/blob/aa488fe074f536f7f36c504c694a75d1f9b4a8e4/src/javascripts/ng-admin/Main/view/layout.html. This demo doesn't aim to demonstrate every possible use cases (it wouldn't be possible), jut one. It's different from the documentation, which already explains how to override the layout (see http://ng-admin-book.marmelab.com/doc/Theming.html). So this demo won't include a layout override.
