### ISSUE TITLE
Angular.js: Error: Module 'MyApp' is not available

### ISSUE THREAD

**Issue by jackzhuo** [marmelab/ng-admin-demo#25]
when I run this demo using "make run", it is OK!

but, when I open the browser (chrome), it can not display correctly, and the console display:
VM394 ng-admin.min.js:24
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

can u help me?

**Comment by jackzhuo** [comment]
there is another error in the browser console,
NumberField.js:1 
Uncaught SyntaxError: Unexpected token import

**Comment by ludoo0d0a** [comment]
Same thing after update dependencies.
I dig into upgrades and found babel 5->6 is a major evolution. 
https://egghead.io/lessons/angularjs-updating-babel-5-to-6.

**Comment by ludoo0d0a** [comment]
I just saw these PR : 
https://github.com/marmelab/ng-admin-demo/pull/26
https://github.com/marmelab/ng-admin/pull/959

so, I wait and see :)

**Comment by Kmaschta** [comment]
These issue and PR are now closed. Sorry for the inconvenience!

Feel free to test with the new versions of `ng-admin` and open an issue again if needed.
