### ISSUE TITLE
How to configure a connection MongoDB

### ISSUE THREAD

**Issue by gcasari** [marmelab/ng-admin-demo#29]
Hello I'm starting to use ng-admin-demo. I want to know how to configure and customize a connection to the datasource mongodb instead of connecting to data.js. There are examples of this? Thanks

**Comment by fzaninotto** [comment]
I'm afraid you're looking at the wrong repo. Head to [marmelab/ng-admin](https://github.com/marmelab/ng-admin), where everything is explained. In particular, the datasource for ng-admin MUST be a REST API. Whether you use mongoDB or another persistence for this API is outside of ng-admin-s scope. 

ng-admin-demo uses a trick to avoid relying on a server for the API - but it's just for the purpose of the demo. Don't look at `data.js` as an example of REST API connection.

**Comment by gcasari** [comment]
Ops ... thanks a lot, I did not see the repo ng-admin. Now I see it
