### ISSUE TITLE
entities with parents id in the URL

### ISSUE THREAD

**Issue by sebest** [marmelab/ng-admin-demo#5]
Hello,

I have API URL like /accounts/:account/applications/:application/tasks/:task/attempts and don't see how to handle this kind of URL with ng-admin.

Any idea?

thanx

**Comment by fzaninotto** [comment]
Duplicate of https://github.com/marmelab/ng-admin/issues/409. Please only open issues in this repo related to the demo itself. For questions and issues about ng-admin, use the ng-admin repository.
